### PR TITLE
Fixes `/issues/new` map_rotation issue

### LINKED ISSUE #268: Creating an issue through `/issues/new` does not handle the plugin correctly.
Firstly calling `@project` to fetch project related information does not work.
The project can be access thorugh`issue.project` though.

With this change the map will not initialize correctly when the project change triggers a dynamic loading of content.

### PR DESCRIPTION
**Pull request by dkastl**
Fixes #268 .

Changes proposed in this pull request:
- Fixes rotation issue
- Fixes access to `@project`

@dkastl @smellman 
I added the followings:
- Adds integration/system tests
- Fixes the following error in #268 description.
  - > With this change the map will not initialize correctly when the project change triggers a dynamic loading of content.

### CODE REVIEW

File: app/helpers/gtt_map_helper.rb [hunk 1]
```diff
@@ -68,6 +68,13 @@ def map_tag(map: nil, layers: map&.layers,
             window.createGttClient(target);
             contentObserver();
           }, { once: true });
+          var target = document.getElementById('#{uid}');
+          if (
+            document.readyState === 'complete'
+            && !target.hasChildNodes()
+          ) {
+            window.createGttClient(target);
+          }
```
Comment (sanak) [inline app/helpers/gtt_map_helper.rb:77]: @smellman (CC: @dkastl)
Related with #257 and PR:#258, I don't know why these changes solve the following error in #268 description.
> With this change the map will not initialize correctly when the project change triggers a dynamic loading of content.

So, reviewing these changes is really helpful. :bow:

Adding `contentObserver()` line caused to generate 2 duplicated maps when clicking on the map, so I don't include the line.

**Review by sanak — APPROVED** [review]
@dkastl (CC: @smellman)
Well, I couldn't set you as reviewer, because I added my commits...
Anyway, I approve this by myself, because I confirmed this.

If there is no strong objection, I am thinking to merge this around this Friday.
