### PR TITLE
Fixes zoom to feature issue when clicking "Quote" link

### LINKED ISSUE #320: Zoom to feature issue when clicking "Quote" link
When the `Quote` link is clicked, the editing of an issue is enabled, but the map does not correctly zoom to extent.

image

### PR DESCRIPTION
**Pull request by dkastl**
Fixes #320 .

Changes proposed in this pull request:
- Extends `handleEditIcon` function to also handle "Quote" links
- Increases timeout to 500ms

### CODE REVIEW

File: src/components/gtt-client/init/events.ts [hunk 1]
```diff
@@ -82,17 +82,17 @@ function handleIssueSelection(this: any): void {
...
-  document.querySelectorAll('div.contextual a.icon-edit').forEach((element: HTMLAnchorElement) => {
+  document.querySelectorAll('div.contextual a.icon-edit, div.contextual a.icon-comment').forEach((element: HTMLAnchorElement) => {
     element.addEventListener('click', () => {
       setTimeout(() => {
         this.maps.forEach((m: any) => {
           m.updateSize();
         });
         zoomToExtent.call(this);
-      }, 200);
+      }, 500);
```
Comment (sanak) [inline src/components/gtt-client/init/events.ts:95]: @dkastl Thanks for the fix!

In my local environment, keeping this `delay` argument's value to original (`200`) was better. (Without showing sea probably around lon,lat = (0, 0)).
Could you check this part a bit ?

| 500ms | 200ms |
|--------|--------|
| redmine-gtt-issue320-setTimeout-delay-500 | redmine-gtt-issue320-setTimeout-delay-200 |

Comment (dkastl) [reply src/components/gtt-client/init/events.ts:95]: Well, I guess that it depends on the device performance eventually, and you have a relatively fast device. We probably need to check on various devices, but in my case 200ms was not enough for the "quote" link case, not on point features either.

Comment (sanak) [reply src/components/gtt-client/init/events.ts:95]: @dkastl (CC: @smellman)
Okay, I reproduced the issue when changing 200ms to 0ms on my environment.
Personally, I think that adjusting timeout delay value is not good idea, and using MutationObserver will be better for such case like issues list view collapsible map.
https://github.com/gtt-project/redmine_gtt/blob/main/src/components/gtt-client/init/events.ts#L28-L47

Comment (dkastl) [reply src/components/gtt-client/init/events.ts:95]: Well, if someone knows, how to implement this with MutationObserver, I agree this is probably more reliable solution. Otherwise, this PR does not really introduce the timeout but just increases the value.

Comment (sanak) [reply src/components/gtt-client/init/events.ts:95]: @dkastl Okay.
I am okay to implement MutationObserver, but it will take a certain time (maybe next week or later), so I approve this.

**Review by sanak — APPROVED** [review]
LGTM! (from discussion)

File: src/components/gtt-client/init/events.ts (hunk 1 above)
Comment (dkastl) [reply src/components/gtt-client/init/events.ts:95]: thanks, I created an issue: https://github.com/gtt-project/redmine_gtt/issues/323
... and will merge this one.
