### PR TITLE
Fixed ActiveRecord::IrreversibleMigration issue when uninstalling plugin

### LINKED ISSUE #21: Uninstall of plugin possible?
The following happens when trying to uninstall `redmine_gtt`:

```
sudo RAILS_ENV=production bundle exec rake db:migrate:plugin NAME=redmine_gtt VERSION=0
Unknown database adapter `postgis` found in config/database.yml, use Gemfile.local to load your own database gems
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /srv/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
Migrating redmine_gtt (Redmine GTT plugin)...
== 20171010022000 AddPositionToGttTileSources: reverting ======================
-- remove_column(:gtt_tile_sources, :position, :integer, {:default=>0})
   -> 0.0009s
== 20171010022000 AddPositionToGttTileSources: reverted (0.0030s) =============

== 20171004054800 EnsureProperSrid: reverting =================================
== 20171004054800 EnsureProperSrid: reverted (0.0000s) ========================

== 20170907013251 AddDefaultValueToGlobalTileSourceField: reverting ===========
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

ActiveRecord::IrreversibleMigration
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration/command_recorder.rb:65:in `inverse_of'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration/command_recorder.rb:50:in `record'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration/command_recorder.rb:83:in `change_column'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/srv/app/plugins/redmine_gtt/db/migrate/20170907013251_add_default_value_to_global_tile_source_field.rb:3:in `change'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:606:in `block in exec_migration'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:495:in `block (2 levels) in revert'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration/command_recorder.rb:38:in `revert'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:495:in `block in revert'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:642:in `suppress_messages'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:494:in `revert'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:606:in `exec_migration'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `ddl_transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:830:in `down'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:805:in `migrate'
/srv/app/lib/redmine/plugin.rb:481:in `migrate_plugin'
/srv/app/lib/redmine/plugin.rb:453:in `migrate'
/srv/app/lib/redmine/plugin.rb:464:in `migrate'
/srv/app/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/srv/app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::IrreversibleMigration: ActiveRecord::IrreversibleMigration
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration/command_recorder.rb:65:in `inverse_of'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration/command_recorder.rb:50:in `record'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration/command_recorder.rb:83:in `change_column'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/srv/app/plugins/redmine_gtt/db/migrate/20170907013251_add_default_value_to_global_tile_source_field.rb:3:in `change'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:606:in `block in exec_migration'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:495:in `block (2 levels) in revert'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration/command_recorder.rb:38:in `revert'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:495:in `block in revert'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:642:in `suppress_messages'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:494:in `revert'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:606:in `exec_migration'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `ddl_transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:830:in `down'
/srv/app/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:805:in `migrate'
/srv/app/lib/redmine/plugin.rb:481:in `migrate_plugin'
/srv/app/lib/redmine/plugin.rb:453:in `migrate'
/srv/app/lib/redmine/plugin.rb:464:in `migrate'
/srv/app/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/srv/app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate:plugin => redmine:plugins:migrate
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by sanak**
Fixes #21.

Changes proposed in this pull request:
- Fixed ActiveRecord::IrreversibleMigration issue when uninstalling plugin

I referred the following Japanese article to solve the issue.
- [migrationでrollback可否でchangeかup/downを使い分ける - Qiita](https://qiita.com/koni4k/items/294342048cb6d47bcc3f)

Here is the way to confirm the fix.
```sh
bundle exec rake db:drop
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake redmine:plugins:migrate
bundle exec rake redmine:plugins:test RAILS_ENV=test NAME=redmine_gtt
bundle exec rake redmine:plugins:migrate VERSION=0 NAME=redmine_gtt
```

@gtt-project/maintainer

### CODE REVIEW

File: db/migrate/20170907013251_add_default_value_to_global_tile_source_field.rb [hunk 1]
```diff
@@ -1,5 +1,9 @@
 class AddDefaultValueToGlobalTileSourceField < ActiveRecord::Migration[5.2]
-  def change
+  def up
     change_column :gtt_tile_sources, :global, :boolean, default: false
   end
+
+  def up
```
Comment (sanak) [inline db/migrate/20170907013251_add_default_value_to_global_tile_source_field.rb:6]: Oops, I missed here...
I will fix this.

Comment (sanak) [reply db/migrate/20170907013251_add_default_value_to_global_tile_source_field.rb]: I fixed this.

**Review by smellman — APPROVED** [review]

File: db/migrate/20170907013251_add_default_value_to_global_tile_source_field.rb (hunk 1 above)
[the remark this answers is not in the document]
Comment (sanak) [reply db/migrate/20170907013251_add_default_value_to_global_tile_source_field.rb]: @smellman Oh, yes. I force pushed the fix (`down`). 🙇 
Thanks for approve!
